import type { CompanyPosting, Industry } from './types';

export const mockCompanies: CompanyPosting[] = [
  {
    id: '1',
    companyName: 'AutoParts India Pvt Ltd',
    industry: 'auto',
    role: 'Auto Mechanic Apprentice',
    location: 'Pune, Maharashtra',
    skillsRequired: ['basic mechanics', 'willingness to learn', '10th pass'],
    trainingProvided: 'Engine repair, electrical systems, diagnostics',
    salaryRange: '₹8,000 - ₹12,000/month',
    duration: '12 months',
    description: 'Leading auto components manufacturer seeking motivated youth for apprenticeship. Full training provided.',
  },
  {
    id: '2',
    companyName: 'BuildRight Constructions',
    industry: 'construction',
    role: 'Masonry & Civil Apprentice',
    location: 'Chennai, Tamil Nadu',
    skillsRequired: ['physical fitness', 'basic math', 'teamwork'],
    trainingProvided: 'Masonry, formwork, safety protocols, blueprint reading',
    salaryRange: '₹9,000 - ₹14,000/month',
    duration: '18 months',
    description: 'Mid-size construction firm. We train from scratch - no experience needed. Clear path to foreman role.',
  },
  {
    id: '3',
    companyName: 'Textile Masters Co',
    industry: 'textiles',
    role: 'Weaving & Dyeing Apprentice',
    location: 'Surat, Gujarat',
    skillsRequired: ['attention to detail', 'hand-eye coordination'],
    trainingProvided: 'Power loom operation, dyeing, quality control',
    salaryRange: '₹7,500 - ₹11,000/month',
    duration: '12 months',
    description: 'Textile export company. Industry-aligned training with guaranteed employment post-apprenticeship.',
  },
  {
    id: '4',
    companyName: 'LogiMove Solutions',
    industry: 'transport',
    role: 'Warehouse & Logistics Apprentice',
    location: 'Bangalore, Karnataka',
    skillsRequired: ['basic computer', 'organizational skills', '12th pass'],
    trainingProvided: 'Inventory management, WMS software, forklift operation',
    salaryRange: '₹10,000 - ₹15,000/month',
    duration: '9 months',
    description: 'E-commerce logistics partner. Learn supply chain operations with growth to supervisor role.',
  },
  {
    id: '5',
    companyName: 'Retail Plus Chain',
    industry: 'retail',
    role: 'Retail Associate Apprentice',
    location: 'Hyderabad, Telangana',
    skillsRequired: ['customer service', 'basic math', 'communication'],
    trainingProvided: 'Sales, inventory, POS systems, visual merchandising',
    salaryRange: '₹8,500 - ₹12,000/month',
    duration: '6 months',
    description: 'Growing retail chain. Fast-track to store manager for high performers.',
  },
  {
    id: '6',
    companyName: 'CareFirst Healthcare',
    industry: 'healthcare',
    role: 'Healthcare Assistant Apprentice',
    location: 'Mumbai, Maharashtra',
    skillsRequired: ['empathy', 'basic science', '12th pass'],
    trainingProvided: 'Patient care, basic nursing, medical equipment, hygiene protocols',
    salaryRange: '₹9,000 - ₹13,000/month',
    duration: '12 months',
    description: 'Nursing home chain. Certified training with placement in our facilities.',
  },
  {
    id: '7',
    companyName: 'Green Motors Workshop',
    industry: 'auto',
    role: 'EV Technician Apprentice',
    location: 'Delhi NCR',
    skillsRequired: ['interest in electric vehicles', '10th pass'],
    trainingProvided: 'EV battery systems, charging infrastructure, diagnostics',
    salaryRange: '₹10,000 - ₹14,000/month',
    duration: '15 months',
    description: 'Future-focused auto workshop. Be part of the EV revolution.',
  },
  {
    id: '8',
    companyName: 'Metro Builders',
    industry: 'construction',
    role: 'Electrical Fitter Apprentice',
    location: 'Kolkata, West Bengal',
    skillsRequired: ['basic electrical interest', 'safety awareness'],
    trainingProvided: 'Wiring, switchgear, safety standards',
    salaryRange: '₹9,500 - ₹13,500/month',
    duration: '12 months',
    description: 'Commercial construction. ITI equivalent training provided.',
  },
];
